const Products = [
  {
    id: 1,
    title: "RED BRICK",
    img: "/product/cofe.jpg",
    description: "Nikmati kopi yang memukau dengan sentuhan kacang almond dan karamel yang seimbang, dipertegas dengan kelezatan buah Los Ancestros untuk pengalaman yang memanjakan lidah Anda.",
    country: "Guatemala",
    flag: "🇬🇹",
    maxOrder: 3,
    price: 11,
    currencyId: "GBP",
    currencyFormat: "£",
    rate: 4.5,
    type: "coffee",
  },
  {
    id: 2,
    title: "TODOS SANTOS",
    img: "/product/copi1.jpg",
    description: "Nikmati kopi yang memukau dengan sentuhan kacang almond dan karamel yang seimbang, dipertegas dengan kelezatan buah Los Ancestros untuk pengalaman yang memanjakan lidah Anda.",
    country: "Guatemala",
    flag: "🇬🇹",
    maxOrder: 3,
    price: 15,
    currencyId: "GBP",
    currencyFormat: "£",
    rate: 4.8,
    type: "coffee",
  },
  {
    id: 3,
    title: "RED DE MUJERES",
    img: "/product/copi2.jpg",
    description: "Nikmati kopi yang memukau dengan sentuhan kacang almond dan karamel yang seimbang, dipertegas dengan kelezatan buah Los Ancestros untuk pengalaman yang memanjakan lidah Anda.",
    country: "Guatemala",
    flag: "🇬🇹",
    maxOrder: 3,
    price: 13,
    currencyId: "GBP",
    currencyFormat: "£",
    rate: 4.3,
    type: "coffee",
  },
  {
    id: 4,
    title: "ORTIZ 1900",
    img: "/product/copi3.jpg",

    description: " Temukan kenikmatan sepanjang hari dengan tekstur krimi kacang pecan yang memikat, disertai sedikit sentuhan anggur merah dan buah ara yang memberikan dimensi baru pada setiap tegukan.",
    country: "Costa Rica",
    flag: "🇨🇷",
    maxOrder: 3,
    price: 15.5,
    currencyId: "GBP",
    currencyFormat: "£",
    rate: 4.5,
    type: "coffee",
  },
  {
    id: 5,
    title: "ARICHA",
    img: "/product/copi5.jpg",
    rate: 4.6,
    description: "Rasakan kelezatan segar, juicy, dan sangat menyenangkan dari Aricha, kopi Ethiopia yang wajib dicoba, memberikan pengalaman minum kopi yang menggugah selera dengan setiap tegukan.",
    country: "Costa Rica",
    flag: "🇨🇷",
    maxOrder: 3,
    price: 15.5,
    currencyId: "GBP",
    currencyFormat: "£",
    type: "coffee",
  },
  {
    id: 6,
    title: "CABALLEROS",
    img: "/product/copi4.jpg",

    description: "Nikmati kopi yang memukau dengan sentuhan kacang almond dan karamel yang seimbang, dipertegas dengan kelezatan buah Los Ancestros untuk pengalaman yang memanjakan lidah Anda.",
    country: "Honduras",
    flag: "🇭🇳",
    maxOrder: 3,
    price: 16,
    currencyId: "GBP",
    currencyFormat: "£",
    rate: 4.9,
    type: "coffee",
  },
  {
    id: 7,
    title: "DECAF ESPRESSO",
    img: "/product/copi9.jpg",
    description: "Menawarkan pengalaman minum kopi yang memikat sepanjang jalan, dengan sensasi buah persik yang berenang dalam karamel dan kustard, memberikan kenikmatan yang tak terlupakan.",
    country: "Ethiopia",
    flag: "🇪🇹",
    maxOrder: 3,
    price: 13.5,
    currencyId: "GBP",
    currencyFormat: "£",
    rate: 5,
    type: "coffee",
  },
  {
    id: 8,
    title: "LA BOLSA",
    img: "/product/copi2.jpg",

    description: "Dengan posisi yang menduduki peringkat tinggi dalam daftar wajib-coba kami, La Bolsa dari Guatemala memberikan pengalaman minum kopi yang tak tertandingi dengan setiap tegukan yang Anda nikmati. ",
    country: "Guatemala",
    flag: "🇬🇹",
    maxOrder: 3,
    price: 13,
    currencyId: "GBP",
    currencyFormat: "£",
    rate: 4.4,
    type: "coffee",
  },
];

export default Products;
